### ISSUE TITLE
Generated aesthetic embeddings missing object attributes

### ISSUE THREAD

**Issue by nielsonm** [AUTOMATIC1111/stable-diffusion-webui-aesthetic-gradients#14]
I generated a .pt file out of ~200 images:
<img width="1000" alt="AG-error" src="https://user-images.githubusercontent.com/967020/201546710-e7133f60-1e45-409e-b0be-39a77cd4f5ae.png">

When I try to use the embedding, I get the following error after less than 3 seconds.
> File "stable-diffusion-webui/extensions/aesthetic-gradients/aesthetic_clip.py", line 233, in __call__
>     sim = text_embs @ img_embs.T
> AttributeError: 'NoneType' object has no attribute 'T'

**Comment by martinobettucci** [comment]
Same here

**Comment by martinobettucci** [comment]
hello @nielsonm , the problem seems like to come from the aesthetic embedding NOT being the same as standard embeddings.
You have to use specifically trained embeddings from AESTETHICS instead of standard prompts embedding.
